# Generated by Django 4.2.4 on 2023-09-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='products.category', verbose_name='Категория'),
        ),
    ]
