# Generated by Django 4.2.4 on 2023-08-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=70, unique=True, verbose_name='URL-имя'),
        ),
    ]
