# Generated by Django 4.2.4 on 2023-09-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=70, unique=True, verbose_name='URL-имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=256, unique=True, verbose_name='URL-имя'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(editable=False, max_length=70, unique=True, verbose_name='URL-имя'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='products.category', verbose_name='Категория'),
        ),
    ]
